name: publish package to npm
on:
  release:
    types:
      - created
jobs:
  publish:
    if: github.repository == 'Erda-FE/dashboard-configuration'
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut code
        uses: actions/checkout@v2
      - name: Setup node env
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish package
        run: npm publish --tag ${{ github.event.release.tag_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Output
        run: echo "@erda-ui/dashboard-configurator@${{ github.event.release.tag_name }} publish successful"
